# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/sckim/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="random"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" "avit" "bira" "bureau" "evan" "gentoo" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=30

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git virtualenvwrapper vi-mode sudo zsh-autosuggestions zsh-syntax-highlighting colored-man-pages z common-aliases python alias-tips emotty battery)

source $ZSH/oh-my-zsh.sh

# User configuration

[[ $TMUX = "" ]] && export TERM="xterm-256color"

export PYENV_ROOT="/projects/SharedFolder/Software/pyenv"
# export MANPATH="/usr/local/man:$MANPATH"
#export PATH="$PATH:/projects/SharedFolder/Software/install/gcc-7.4.0/bin"
export PATH="$PYENV_ROOT/bin:$PATH:$HOME/bin:/usr/local/cuda-10.0/bin:/usr/lib64/openmpi/bin"
export PATH="$PATH:/projects/SharedFolder/Software/mirdeep2/bin:/projects/SharedFolder/Software/bbmap:/projects/SharedFolder/Software/edirect:/projects/SharedFolder/Software/install/bin"
export PATH="$PATH:$HOME/.rvm/bin"
#export CCACHE_PATH="/projects/SharedFolder/Software/install/gcc-7.4.0/bin"

PERL_MB_OPT="--install_base /home/sckim/perl5";export PERL_MB_OPT
PERL_MM_OPT="INSTALL_BASE=/home/sckim/perl5";export PERL_MM_OPT
export PERL5LIB="/projects/SharedFolder/Software/mirdeep2/lib/perl5"

#export LD_LIBRARY_PATH="/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/extras/CUPTI/lib64:/projects/SharedFolder/Software/install/gcc-7.4.0/lib64:/usr/local/lib:$LD_LIBRARY_PATH:/usr/lib64/openmpi/lib"
export LD_LIBRARY_PATH="/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:/usr/local/lib:$LD_LIBRARY_PATH:/usr/lib64/openmpi/lib"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"
export RSTUDIO_WHICH_R="/projects/SharedFolder/Software/install/R-3.6.0/bin/R"
export CCACHE_DIR="/projects/sckim/.ccache"
export JAVA_HOME="/usr/lib/jvm/java-1.8.0-oracle-1.8.0.201-1jpp.3.el7.x86_64"
export PYJNIUS_JAR="/projects/SharedFolder/Software/pyjnius/build/pyjnius.jar"
export OMP_NUM_THREADS=8
export SMS=50
export PYTHON_CONFIGURE_OPTS="--enable-shared"
export CUDA_HOME=/usr/local/cuda-10.0
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/local/cuda/pkgconfig:/usr/local/lib64/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig:/usr/lib64/pkgconfig

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias jn="jupyter notebook"
alias duf="du -sh * | sort -k1 -h -r"
alias R="/projects/SharedFolder/Software/install/R-3.6.0/bin/R"
alias Rscript="/projects/SharedFolder/Software/install/R-3.6.0/bin/Rscript"
alias mR="/opt/microsoft/ropen/3.5.3/lib64/R/bin/R"
alias loadopenfoam='source /projects/SharedFolder/Software/OpenFOAM/OpenFOAM-2.3.0/etc/bashrc'
alias lmp_4core="mpirun -np 4 /projects/SharedFolder/Software/lammps/build/lmp_mpi"
alias lmp_8core="mpirun -np 8 /projects/SharedFolder/Software/lammps/build/lmp_mpi"
alias lmp_12core="mpirun -np 12 /projects/SharedFolder/Software/lammps/build/lmp_mpi"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
fpath+=${ZDOTDIR:-~}/.zsh_functions

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  source $(pyenv root)/completions/pyenv.zsh
fi
